# Generated by Django 6.0.7 on 2026-07-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_invitation_status_alter_organization_is_active'),
        ('projects', '0003_project_created_at_project_description_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_project_per_org'),
        ),
    ]
