# Generated by Django 6.0.7 on 2026-08-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_exportjob_type_projectmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
