# Generated by Django 6.0.7 on 2026-08-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_exportjob_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='type',
            field=models.CharField(choices=[('CSV', 'CSV')], default='CSV', max_length=20),
        ),
    ]
