[mypy]
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

python_version = 3.13
ignore_missing_imports = True
check_untyped_defs = True
warn_unused_ignores = True
warn_redundant_casts = True
show_error_codes = True

[mypy.plugins.django-stubs]
django_settings_module = config.settings.dev

[mypy-accounts.models]
disable_error_code = attr-defined,assignment,misc