# Generated by Django 6.0.7 on 2026-08-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_invitation_status_alter_organization_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('GUEST', 'Guest')], default='MEMBER', max_length=20),
        ),
    ]
