# Generated by Django 6.0.7 on 2026-08-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_backfill_task_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
